/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Standard two letter continent code
	  
	 ADDED IN 1.6 */
@org.apache.avro.specific.AvroGenerated
public enum FL_ContinentCode { 
  AF, AS, EU, NA, SA, OC, AN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_ContinentCode\",\"namespace\":\"influent.idl\",\"doc\":\"Standard two letter continent code\\r\\n\\t  \\r\\n\\t ADDED IN 1.6\",\"symbols\":[\"AF\",\"AS\",\"EU\",\"NA\",\"SA\",\"OC\",\"AN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
