/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Temporal resolution of a duratino
	 
	 CHANGED IN 1.5 */
@org.apache.avro.specific.AvroGenerated
public enum FL_DateInterval { 
  SECONDS, HOURS, DAYS, WEEKS, MONTHS, QUARTERS, YEARS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_DateInterval\",\"namespace\":\"influent.idl\",\"doc\":\"Temporal resolution of a duratino\\r\\n\\t \\r\\n\\t CHANGED IN 1.5\",\"symbols\":[\"SECONDS\",\"HOURS\",\"DAYS\",\"WEEKS\",\"MONTHS\",\"QUARTERS\",\"YEARS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
