/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** A temporal duration
	 
	 ADDED IN 1.5 */
@org.apache.avro.specific.AvroGenerated
public class FL_Duration extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FL_Duration\",\"namespace\":\"influent.idl\",\"doc\":\"A temporal duration\\r\\n\\t \\r\\n\\t ADDED IN 1.5\",\"fields\":[{\"name\":\"interval\",\"type\":{\"type\":\"enum\",\"name\":\"FL_DateInterval\",\"doc\":\"Temporal resolution of a duratino\\r\\n\\t \\r\\n\\t CHANGED IN 1.5\",\"symbols\":[\"SECONDS\",\"HOURS\",\"DAYS\",\"WEEKS\",\"MONTHS\",\"QUARTERS\",\"YEARS\"]},\"doc\":\"time aggregation level, e.g. use monthly data\"},{\"name\":\"numIntervals\",\"type\":\"long\",\"doc\":\"number of intervals, e.g. 12 monthly intervals is a 1 year duration\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** time aggregation level, e.g. use monthly data */
   private influent.idl.FL_DateInterval interval;
  /** number of intervals, e.g. 12 monthly intervals is a 1 year duration */
   private long numIntervals;

  /**
   * Default constructor.
   */
  public FL_Duration() {}

  /**
   * All-args constructor.
   */
  public FL_Duration(influent.idl.FL_DateInterval interval, java.lang.Long numIntervals) {
    this.interval = interval;
    this.numIntervals = numIntervals;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return interval;
    case 1: return numIntervals;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: interval = (influent.idl.FL_DateInterval)value$; break;
    case 1: numIntervals = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'interval' field.
   * time aggregation level, e.g. use monthly data   */
  public influent.idl.FL_DateInterval getInterval() {
    return interval;
  }

  /**
   * Sets the value of the 'interval' field.
   * time aggregation level, e.g. use monthly data   * @param value the value to set.
   */
  public void setInterval(influent.idl.FL_DateInterval value) {
    this.interval = value;
  }

  /**
   * Gets the value of the 'numIntervals' field.
   * number of intervals, e.g. 12 monthly intervals is a 1 year duration   */
  public java.lang.Long getNumIntervals() {
    return numIntervals;
  }

  /**
   * Sets the value of the 'numIntervals' field.
   * number of intervals, e.g. 12 monthly intervals is a 1 year duration   * @param value the value to set.
   */
  public void setNumIntervals(java.lang.Long value) {
    this.numIntervals = value;
  }

  /** Creates a new FL_Duration RecordBuilder */
  public static influent.idl.FL_Duration.Builder newBuilder() {
    return new influent.idl.FL_Duration.Builder();
  }
  
  /** Creates a new FL_Duration RecordBuilder by copying an existing Builder */
  public static influent.idl.FL_Duration.Builder newBuilder(influent.idl.FL_Duration.Builder other) {
    return new influent.idl.FL_Duration.Builder(other);
  }
  
  /** Creates a new FL_Duration RecordBuilder by copying an existing FL_Duration instance */
  public static influent.idl.FL_Duration.Builder newBuilder(influent.idl.FL_Duration other) {
    return new influent.idl.FL_Duration.Builder(other);
  }
  
  /**
   * RecordBuilder for FL_Duration instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FL_Duration>
    implements org.apache.avro.data.RecordBuilder<FL_Duration> {

    private influent.idl.FL_DateInterval interval;
    private long numIntervals;

    /** Creates a new Builder */
    private Builder() {
      super(influent.idl.FL_Duration.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(influent.idl.FL_Duration.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing FL_Duration instance */
    private Builder(influent.idl.FL_Duration other) {
            super(influent.idl.FL_Duration.SCHEMA$);
      if (isValidValue(fields()[0], other.interval)) {
        this.interval = data().deepCopy(fields()[0].schema(), other.interval);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numIntervals)) {
        this.numIntervals = data().deepCopy(fields()[1].schema(), other.numIntervals);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'interval' field */
    public influent.idl.FL_DateInterval getInterval() {
      return interval;
    }
    
    /** Sets the value of the 'interval' field */
    public influent.idl.FL_Duration.Builder setInterval(influent.idl.FL_DateInterval value) {
      validate(fields()[0], value);
      this.interval = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'interval' field has been set */
    public boolean hasInterval() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'interval' field */
    public influent.idl.FL_Duration.Builder clearInterval() {
      interval = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'numIntervals' field */
    public java.lang.Long getNumIntervals() {
      return numIntervals;
    }
    
    /** Sets the value of the 'numIntervals' field */
    public influent.idl.FL_Duration.Builder setNumIntervals(long value) {
      validate(fields()[1], value);
      this.numIntervals = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'numIntervals' field has been set */
    public boolean hasNumIntervals() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'numIntervals' field */
    public influent.idl.FL_Duration.Builder clearNumIntervals() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public FL_Duration build() {
      try {
        FL_Duration record = new FL_Duration();
        record.interval = fieldSetFlags()[0] ? this.interval : (influent.idl.FL_DateInterval) defaultValue(fields()[0]);
        record.numIntervals = fieldSetFlags()[1] ? this.numIntervals : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
