/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** * This is the current list of tags for Entities:
	 *
	 * CHANGED in 1.6:
	 * - added ACCOUNT_OWNER, CLUSTER_SUMMARY
	 *
	 * CHANGED in 1.7:
	 * - added PROMPT_FOR_DETAILS
	 *
	 * CHANGED in 1.8:
	 * - added UNBRANCHABLE */
@org.apache.avro.specific.AvroGenerated
public enum FL_EntityTag { 
  ACCOUNT_OWNER, ACCOUNT, GROUP, CLUSTER, CLUSTER_SUMMARY, FILE, ANONYMOUS, UNBRANCHABLE, PROMPT_FOR_DETAILS, OTHER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_EntityTag\",\"namespace\":\"influent.idl\",\"doc\":\"* This is the current list of tags for Entities:\\r\\n\\t *\\r\\n\\t * CHANGED in 1.6:\\r\\n\\t * - added ACCOUNT_OWNER, CLUSTER_SUMMARY\\r\\n\\t *\\r\\n\\t * CHANGED in 1.7:\\r\\n\\t * - added PROMPT_FOR_DETAILS\\r\\n\\t *\\r\\n\\t * CHANGED in 1.8:\\r\\n\\t * - added UNBRANCHABLE\",\"symbols\":[\"ACCOUNT_OWNER\",\"ACCOUNT\",\"GROUP\",\"CLUSTER\",\"CLUSTER_SUMMARY\",\"FILE\",\"ANONYMOUS\",\"UNBRANCHABLE\",\"PROMPT_FOR_DETAILS\",\"OTHER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
