/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Amount of detail requested
	 
	 ADDED IN 1.6 */
@org.apache.avro.specific.AvroGenerated
public enum FL_LevelOfDetail { 
  SUMMARY, FULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_LevelOfDetail\",\"namespace\":\"influent.idl\",\"doc\":\"Amount of detail requested\\r\\n\\t \\r\\n\\t ADDED IN 1.6\",\"symbols\":[\"SUMMARY\",\"FULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
