/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;

@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public interface FL_Persistence {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FL_Persistence\",\"namespace\":\"influent.idl\",\"doc\":\"\",\"types\":[{\"type\":\"enum\",\"name\":\"FL_PersistenceState\",\"doc\":\"Persistence save state\",\"symbols\":[\"NEW\",\"MODIFIED\",\"NONE\",\"ERROR\"]}],\"messages\":{\"persistData\":{\"doc\":\"Saves the client state given a session UID.\\r\\n\\t \\r\\n\\t Service URL: /persist\\r\\n\\t HTTP Method: POST\\r\\n\\t \\r\\n\\t @param sessionId \\t\\tsession uid\\r\\n\\t @param data \\t\\t\\tstring representation of client state\\r\\n\\t @return\\t\\t\\t\\tstate of persistence for the sessionId\",\"request\":[{\"name\":\"sessionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"data\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":\"FL_PersistenceState\"},\"getData\":{\"doc\":\"Returns the last saved client state given a session UID.\\r\\n\\t \\r\\n\\t Service URL: /persist\\r\\n\\t HTTP Method: GET\\r\\n\\t \\r\\n\\t @param sessionId \\t\\tsession uid\\r\\n\\t @return \\t\\t\\t\\tclient state data\",\"request\":[{\"name\":\"sessionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"response\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}}");
  /** Saves the client state given a session UID.
	 
	 Service URL: /persist
	 HTTP Method: POST
	 
	 @param sessionId 		session uid
	 @param data 			string representation of client state
	 @return				state of persistence for the sessionId */
  influent.idl.FL_PersistenceState persistData(java.lang.String sessionId, java.lang.String data) throws org.apache.avro.AvroRemoteException;
  /** Returns the last saved client state given a session UID.
	 
	 Service URL: /persist
	 HTTP Method: GET
	 
	 @param sessionId 		session uid
	 @return 				client state data */
  java.lang.String getData(java.lang.String sessionId) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /**  */
  public interface Callback extends FL_Persistence {
    public static final org.apache.avro.Protocol PROTOCOL = influent.idl.FL_Persistence.PROTOCOL;
    /** Saves the client state given a session UID.
	 
	 Service URL: /persist
	 HTTP Method: POST
	 
	 @param sessionId 		session uid
	 @param data 			string representation of client state
	 @return				state of persistence for the sessionId */
    void persistData(java.lang.String sessionId, java.lang.String data, org.apache.avro.ipc.Callback<influent.idl.FL_PersistenceState> callback) throws java.io.IOException;
    /** Returns the last saved client state given a session UID.
	 
	 Service URL: /persist
	 HTTP Method: GET
	 
	 @param sessionId 		session uid
	 @return 				client state data */
    void getData(java.lang.String sessionId, org.apache.avro.ipc.Callback<java.lang.String> callback) throws java.io.IOException;
  }
}