/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** * Allowed types for Property values.
	 *
	 * CHANGED in 1.9 */
@org.apache.avro.specific.AvroGenerated
public enum FL_PropertyType { 
  FLOAT, DOUBLE, INTEGER, LONG, BOOLEAN, STRING, IMAGE, DATE, GEO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_PropertyType\",\"namespace\":\"influent.idl\",\"doc\":\"* Allowed types for Property values.\\r\\n\\t *\\r\\n\\t * CHANGED in 1.9\",\"symbols\":[\"FLOAT\",\"DOUBLE\",\"INTEGER\",\"LONG\",\"BOOLEAN\",\"STRING\",\"IMAGE\",\"DATE\",\"GEO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
