/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** * A list of the required property keys that are reserved by the system and should be included as
	 * the keys in FL_PropertyMatchDescriptors. Keys are case sensitive.
	 *
	 * ADDED IN 2.0 */
@org.apache.avro.specific.AvroGenerated
public enum FL_RequiredPropertyKey { 
  NAME, ID, FROM, TO, DATE, AMOUNT, ENTITY, LINKED, TYPE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_RequiredPropertyKey\",\"namespace\":\"influent.idl\",\"doc\":\"* A list of the required property keys that are reserved by the system and should be included as\\r\\n\\t * the keys in FL_PropertyMatchDescriptors. Keys are case sensitive.\\r\\n\\t *\\r\\n\\t * ADDED IN 2.0\",\"symbols\":[\"NAME\",\"ID\",\"FROM\",\"TO\",\"DATE\",\"AMOUNT\",\"ENTITY\",\"LINKED\",\"TYPE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
