/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** * A list of case sensitive keys which are reserved keywords in search.
	 *
	 * ADDED IN 2.0 */
@org.apache.avro.specific.AvroGenerated
public enum FL_ReservedPropertyKey { 
  TYPE, ORDER, MATCH, SCORE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_ReservedPropertyKey\",\"namespace\":\"influent.idl\",\"doc\":\"* A list of case sensitive keys which are reserved keywords in search.\\r\\n\\t *\\r\\n\\t * ADDED IN 2.0\",\"symbols\":[\"TYPE\",\"ORDER\",\"MATCH\",\"SCORE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
