/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Allowed types for Ranges of values.
	
	CHANGED IN 1.6 */
@org.apache.avro.specific.AvroGenerated
public enum FL_RangeType { 
  SINGLETON, LIST, BOUNDED, DISTRIBUTION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_RangeType\",\"namespace\":\"influent.idl\",\"doc\":\"Allowed types for Ranges of values.\\r\\n\\t\\r\\n\\tCHANGED IN 1.6\",\"symbols\":[\"SINGLETON\",\"LIST\",\"BOUNDED\",\"DISTRIBUTION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
