/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** * Used to describe in which contexts a term can (or should) be searched. Free text searches
	 * do not describe properties to which they apply, and are often best restricted to
	 * identity fields like names.
	 *
	 * ADDED IN 1.8
	 * MOVED IN 2.0 */
@org.apache.avro.specific.AvroGenerated
public enum FL_SearchableBy { 
  FREE_TEXT, DESCRIPTOR, NONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_SearchableBy\",\"namespace\":\"influent.idl\",\"doc\":\"* Used to describe in which contexts a term can (or should) be searched. Free text searches\\r\\n\\t * do not describe properties to which they apply, and are often best restricted to\\r\\n\\t * identity fields like names.\\r\\n\\t *\\r\\n\\t * ADDED IN 1.8\\r\\n\\t * MOVED IN 2.0\",\"symbols\":[\"FREE_TEXT\",\"DESCRIPTOR\",\"NONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
